#define CUTELEE_VERSION_MAJOR @Cutelee_VERSION_MAJOR@
#define CUTELEE_VERSION_MINOR @Cutelee_VERSION_MINOR@
#define CUTELEE_VERSION_PATCH @Cutelee_VERSION_PATCH@
#define CUTELEE_VERSION_STRING "@Cutelee_VERSION@"
#define CUTELEE_MAJOR_MINOR_VERSION_STRING "@Cutelee_MAJOR_MINOR_VERSION_STRING@"
#define CUTELEE_MIN_PLUGIN_VERSION @Cutelee_MIN_PLUGIN_VERSION@
#define QT_VERSION_MAJOR @QT_VERSION_MAJOR@
