#define CUTELEE_VERSION_MAJOR @Cutelee5_VERSION_MAJOR@
#define CUTELEE_VERSION_MINOR @Cutelee5_VERSION_MINOR@
#define CUTELEE_VERSION_PATCH @Cutelee5_VERSION_PATCH@
#define CUTELEE_VERSION_STRING "@Cutelee5_VERSION@"
#define CUTELEE_MAJOR_MINOR_VERSION_STRING "@Cutelee5_MAJOR_MINOR_VERSION_STRING@"
#define CUTELEE_MIN_PLUGIN_VERSION @Cutelee5_MIN_PLUGIN_VERSION@
